### ISSUE TITLE
Vote some Delegates of Lisk to earn forging rewards

### ISSUE THREAD

**Issue by kalgoop** [ICNHodler/IIPs#5]
As the heading says, Iconomi can increase the number of Lisk they own by voting for delegates on lisk, which will give some forged Lisk in return.

According to my calculations,  it can amount to **burning of 124K more ICN /Month**. Which is a very good amount.

Sources: [icnhodler.com](https://icnhodler.com) and [earnlisk.com](https://earnlisk.com)

**Comment by jesusthatsgreat** [comment]
@kalgoop yes, the idea of staking / voting with various assets makes sense in my opinion if the assets are gong to be held long term anyway.

**Comment by jesusthatsgreat** [comment]
Closing this as they started voting in Q4 👍 https://explorer.lisk.io/address/9094944264474023843L
